version: '3'
services:
  bitcoind:
    image: coblox/bitcoin-core:0.21.0
    container_name: bitcoind
    entrypoint:
      - /usr/bin/bitcoind
    command:
      - -server
      - -regtest
      - -txindex=1
      - -listen=1
      - -prune=0
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=admin
      - -rpcpassword=123
      - -printtoconsole
      - -rest
      - -fallbackfee=0.0002
      - -datadir=/home/bdk-test
      - -rpcport=18443 # default port. just for documentation purpose
      - -port=18886
      - -rest
    ports:
      - 7041:18443
      - 7042:18886
    volumes:
      - data:/home/bdk-test
  electrs:
    image: vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvvv
      - --network=regtest
      - --daemon-dir=/home/bdk-test/
      - --daemon-rpc-addr=bitcoind:18443
      - --cookie=admin:123
      - --http-addr=0.0.0.0:3002
      - --electrum-rpc-addr=0.0.0.0:60401
      - --cors="*"
    depends_on:
      - bitcoind
    ports:
      - 60401:60401
      - 3012:3002
    volumes:
      - data:/home/bdk-test

volumes:
  data:
